-- ============================================================================
-- COACH DM — Seed 008 : 120+ exercices trilingues science-based
-- ============================================================================
-- Code couleur tip aligné sur les standards PDFs:
--   green = insight (référence scientifique clé)
--   red   = warning (erreur fréquente / risque blessure)
--   blue  = info (donnée chiffrée, norme pro)
--   violet= tactic (application directe sport/compétition)
-- ============================================================================

insert into public.exercises (
  slug, name_fr, name_en, name_nl, pattern, modality, difficulty,
  primary_muscles, secondary_muscles, goals,
  cues_fr, cues_en, cues_nl,
  tip_color, tip_fr, tip_en, tip_nl, reference_citation,
  default_tempo, is_unilateral, requires_spotter
) values

-- ============================== SQUAT FAMILY ==============================
('back-squat','Back Squat','Back Squat','Back Squat','squat','barbell','intermediate',
 array['quadriceps','glutes'], array['hamstrings','core','erectors'],
 array['fat_loss','strength','functional','sport']::workout_goal[],
 'Pieds largeur épaules, descends jusqu''à hanches sous genoux, dos neutre, poussée talons.',
 'Feet shoulder-width, descend until hips below knees, neutral spine, drive through heels.',
 'Voeten op schouderbreedte, daal tot heupen onder knieën, rug neutraal, druk via hielen.',
 'green',
 'Le squat profond active 25% de glutes en plus que le squat parallèle.',
 'Deep squat activates 25% more glutes than parallel squat.',
 'Diepe squat activeert 25% meer bilspieren dan parallel squat.',
 'Schoenfeld 2010', '3-1-1-0', false, true),

('front-squat','Front Squat','Front Squat','Front Squat','squat','barbell','advanced',
 array['quadriceps','core'], array['glutes','upper_back'],
 array['strength','functional','sport']::workout_goal[],
 'Barre sur deltoïdes, coudes hauts, torse vertical, descends en gardant la barre stable.',
 'Bar on delts, elbows high, torso vertical, descend keeping the bar stable.',
 'Stang op deltoïden, ellebogen hoog, romp verticaal, daal met stabiele stang.',
 'blue',
 'Sollicite 30-50% de plus le quadriceps que le back squat à charge égale.',
 'Recruits 30-50% more quadriceps than back squat at equal load.',
 'Belast 30-50% meer quadriceps dan back squat bij gelijke belasting.',
 'Gullett 2009', '3-1-1-0', false, true),

('goblet-squat','Goblet Squat','Goblet Squat','Goblet Squat','squat','dumbbell','beginner',
 array['quadriceps','glutes'], array['core'],
 array['fat_loss','functional','travel_home','mobility']::workout_goal[],
 'Hold un haltère contre la poitrine, coudes vers les genoux, descends profond.',
 'Hold a dumbbell at chest, elbows toward knees, descend deep.',
 'Houd halter op borst, ellebogen naar knieën, daal diep.',
 'blue',
 'Position idéale pour apprendre le squat sans charger la colonne.',
 'Ideal position to learn the squat without loading the spine.',
 'Ideale houding om squat te leren zonder de wervelkolom te belasten.',
 'Cook 2010', '3-1-1-0', false, false),

('overhead-squat','Overhead Squat','Overhead Squat','Overhead Squat','squat','barbell','advanced',
 array['quadriceps','glutes','shoulders'], array['core','upper_back'],
 array['functional','sport']::workout_goal[],
 'Barre verrouillée bras tendus au-dessus, prise large, descends profond, regard avant.',
 'Bar locked overhead, wide grip, descend deep, eyes forward.',
 'Stang vergrendeld boven hoofd, brede greep, daal diep, blik vooruit.',
 'green',
 'Test gold-standard de mobilité globale (FMS).',
 'Gold-standard global mobility test (FMS).',
 'Gouden standaard test van algehele mobiliteit (FMS).',
 'Cook FMS', '3-1-1-0', false, false),

('bulgarian-split-squat','Squat Bulgare','Bulgarian Split Squat','Bulgaarse Split Squat','lunge','dumbbell','intermediate',
 array['quadriceps','glutes'], array['hamstrings','core'],
 array['fat_loss','strength','sport']::workout_goal[],
 'Pied arrière en hauteur, descends genou avant à 90°, torse droit.',
 'Rear foot elevated, descend front knee to 90°, torso upright.',
 'Achterste voet verhoogd, voorste knie naar 90°, romp rechtop.',
 'violet',
 'Réduit asymétries jambe droite/gauche, clé pour foot et hyrox.',
 'Reduces left/right leg asymmetries, key for football and Hyrox.',
 'Vermindert links/rechts been-asymmetrieën, sleutel voor voetbal en Hyrox.',
 'McCurdy 2010', '3-1-1-0', true, false),

('lunge-walking','Fente Marchée','Walking Lunge','Wandelende Lunge','lunge','dumbbell','beginner',
 array['quadriceps','glutes'], array['hamstrings','core'],
 array['fat_loss','functional','travel_home']::workout_goal[],
 'Avance, genou avant à 90°, genou arrière touche presque le sol, alterne.',
 'Step forward, front knee 90°, rear knee almost touches floor, alternate.',
 'Stap voorwaarts, voorste knie 90°, achterste knie raakt bijna grond, wissel.',
 'blue', null, null, null, null, '2-0-1-0', true, false),

('reverse-lunge','Fente Arrière','Reverse Lunge','Achterwaartse Lunge','lunge','dumbbell','beginner',
 array['glutes','quadriceps'], array['hamstrings','core'],
 array['fat_loss','functional','travel_home']::workout_goal[],
 'Recule la jambe, descends genou arrière, plus doux pour les genoux que la fente avant.',
 'Step back, lower rear knee, easier on knees than forward lunge.',
 'Stap achterwaarts, laat achterste knie zakken, makkelijker voor knieën dan voorwaartse lunge.',
 'green',
 'Réduit le stress sur le genou avant de 30% vs fente avant.',
 'Reduces front knee stress by 30% vs forward lunge.',
 'Vermindert stress op voorste knie met 30% vs voorwaartse lunge.',
 'Riemann 2012', '2-0-1-0', true, false),

('pistol-squat','Pistol Squat','Pistol Squat','Pistol Squat','squat','bodyweight','advanced',
 array['quadriceps','glutes'], array['core','calves'],
 array['functional','sport','travel_home']::workout_goal[],
 'Une jambe tendue devant, descends complet sur l''autre, contrôle total.',
 'One leg straight in front, descend fully on other leg, full control.',
 'Eén been gestrekt vooruit, daal volledig op andere been, volledige controle.',
 'red',
 'Ne pas tenter sans 6 mois de squat/lunges et mobilité cheville suffisante.',
 'Do not attempt without 6 months of squat/lunge work and adequate ankle mobility.',
 'Niet proberen zonder 6 maanden squat/lunge werk en voldoende enkelmobiliteit.',
 null, '3-1-1-0', true, false),

('air-squat','Air Squat','Air Squat','Air Squat','squat','bodyweight','beginner',
 array['quadriceps','glutes'], array['core'],
 array['fat_loss','functional','travel_home']::workout_goal[],
 'Sans charge, descends profond, genoux suivent les pieds, talons au sol.',
 'No load, descend deep, knees track over toes, heels grounded.',
 'Geen belasting, daal diep, knieën volgen tenen, hielen op grond.',
 'blue', null, null, null, null, '2-0-1-0', false, false),

('jump-squat','Jump Squat','Jump Squat','Jump Squat','jump','bodyweight','intermediate',
 array['quadriceps','glutes'], array['calves','core'],
 array['fat_loss','sport','functional']::workout_goal[],
 'Squat dynamique, explose vers le haut, atterris souple.',
 'Dynamic squat, explode upward, land softly.',
 'Dynamische squat, explosief omhoog, zacht landen.',
 'violet',
 'Améliore vitesse de sprint de 3-5% en 6 semaines (footballeurs).',
 'Improves sprint speed by 3-5% in 6 weeks (footballers).',
 'Verbetert sprintsnelheid met 3-5% in 6 weken (voetballers).',
 'Markovic 2007', null, false, false),

-- ============================== HINGE FAMILY ==============================
('deadlift','Soulevé de Terre','Deadlift','Deadlift','hinge','barbell','intermediate',
 array['hamstrings','glutes','erectors'], array['lats','core','traps'],
 array['strength','functional','sport']::workout_goal[],
 'Pieds sous la barre, hanches en arrière, dos neutre, pousse le sol.',
 'Feet under bar, hips back, neutral spine, drive the floor away.',
 'Voeten onder stang, heupen achterwaarts, rug neutraal, duw de grond weg.',
 'red',
 'Dos arrondi sous charge = première cause de hernie discale en salle.',
 'Rounded back under load = leading cause of disc hernia in gym.',
 'Afgeronde rug onder belasting = belangrijkste oorzaak van discushernia in sportschool.',
 'McGill 2014', '2-1-1-0', false, false),

('romanian-deadlift','Soulevé Roumain','Romanian Deadlift','Romeinse Deadlift','hinge','barbell','intermediate',
 array['hamstrings','glutes'], array['erectors','lats'],
 array['strength','sport']::workout_goal[],
 'Légère flexion genoux, hanches en arrière, barre près du corps, étirement ischios.',
 'Slight knee bend, hips back, bar close to body, hamstring stretch.',
 'Lichte kniebuiging, heupen achterwaarts, stang dicht bij lichaam, hamstring strek.',
 'green',
 'Allonge les ischios sous tension, recommandé en post-rééduc.',
 'Lengthens hamstrings under tension, recommended post-rehab.',
 'Verlengt hamstrings onder spanning, aanbevolen na revalidatie.',
 'Schoenfeld 2015', '3-1-1-0', false, false),

('trap-bar-deadlift','Soulevé Trap Bar','Trap Bar Deadlift','Trap Bar Deadlift','hinge','barbell','beginner',
 array['quadriceps','glutes','hamstrings'], array['erectors','traps'],
 array['strength','functional','sport']::workout_goal[],
 'Position centrée dans la trap, dos neutre, pousse le sol, plus sûr que le DL conventionnel.',
 'Centered in trap bar, neutral spine, drive floor, safer than conventional DL.',
 'Centraal in trap bar, rug neutraal, duw grond, veiliger dan conventionele DL.',
 'green',
 'Méthode Liverpool FC pour développer la puissance sans surcharger la colonne.',
 'Liverpool FC method to develop power without overloading the spine.',
 'Liverpool FC methode om kracht te ontwikkelen zonder de wervelkolom te overbelasten.',
 'Kornmayer S&C', '2-1-1-0', false, false),

('kb-swing','Kettlebell Swing','Kettlebell Swing','Kettlebell Swing','hinge','kettlebell','beginner',
 array['glutes','hamstrings'], array['core','shoulders'],
 array['fat_loss','functional','travel_home','sport']::workout_goal[],
 'Hip hinge, propulsion par les hanches, kettlebell jusqu''aux yeux, dos neutre.',
 'Hip hinge, propulsion from hips, kettlebell to eye level, neutral spine.',
 'Heupkanteling, voortstuwing vanuit heupen, kettlebell tot ooghoogte, rug neutraal.',
 'blue',
 '20min de swings = 1200 kcal/h selon ACE Fitness.',
 '20min of swings = 1200 kcal/h per ACE Fitness.',
 '20 minuten swings = 1200 kcal/u volgens ACE Fitness.',
 'Porcari ACE 2010', null, false, false),

('good-morning','Good Morning','Good Morning','Good Morning','hinge','barbell','intermediate',
 array['hamstrings','erectors'], array['glutes'],
 array['strength','sport']::workout_goal[],
 'Barre sur le haut du dos, hanches en arrière, descends torse, charge légère.',
 'Bar on upper back, hips back, lower torso, light load.',
 'Stang op bovenrug, heupen achterwaarts, romp neerwaarts, lichte belasting.',
 'red',
 'Charge max 30% du back squat — risque blessure dorso-lombaire élevé.',
 'Max load 30% of back squat — high lumbar injury risk.',
 'Maximale belasting 30% van back squat — hoog lumbaal blessurerisico.',
 'McGill 2014', '3-1-1-0', false, false),

('hip-thrust','Hip Thrust','Hip Thrust','Hip Thrust','hinge','barbell','intermediate',
 array['glutes'], array['hamstrings','core'],
 array['fat_loss','strength','sport']::workout_goal[],
 'Dos sur banc, barre sur hanches, pousse le sol, contracte glutes en haut 1s.',
 'Back on bench, bar on hips, drive floor, squeeze glutes at top 1s.',
 'Rug op bank, stang op heupen, duw grond, knijp bilspieren bovenaan 1s.',
 'green',
 'Active 70-80% des fessiers (EMG) — record toutes méthodes confondues.',
 'Activates 70-80% of glutes (EMG) — record across all methods.',
 'Activeert 70-80% van bilspieren (EMG) — record over alle methoden.',
 'Contreras 2017', '3-1-2-0', false, false),

('single-leg-rdl','Soulevé Roumain Unilatéral','Single-Leg RDL','Single-Leg RDL','hinge','dumbbell','intermediate',
 array['hamstrings','glutes'], array['core'],
 array['sport','functional','mobility']::workout_goal[],
 'Sur une jambe, descends torse + jambe arrière en parallèle au sol, équilibre.',
 'On one leg, lower torso + rear leg parallel to floor, balance.',
 'Op één been, breng romp + achterste been parallel aan vloer, evenwicht.',
 'violet',
 'Réduit risque blessure ischios de 50% chez footballeurs.',
 'Reduces hamstring injury risk by 50% in footballers.',
 'Vermindert hamstringblessurerisico met 50% bij voetballers.',
 'Mendiguchia 2017', '3-1-1-0', true, false),

('nordic-hamstring','Nordic Hamstring','Nordic Hamstring','Nordic Hamstring','hinge','bodyweight','advanced',
 array['hamstrings'], array['glutes','core'],
 array['sport']::workout_goal[],
 'À genoux, pieds bloqués, descends lentement vers l''avant, contrôle excentrique max.',
 'Kneeling, feet anchored, lower slowly forward, max eccentric control.',
 'Op knieën, voeten verankerd, daal langzaam voorwaarts, max excentrische controle.',
 'green',
 'Réduit blessures ischios de 51% (méta-analyse 8459 athlètes).',
 'Reduces hamstring injuries by 51% (meta-analysis 8459 athletes).',
 'Vermindert hamstringblessures met 51% (meta-analyse 8459 atleten).',
 'Askling 2003 / van Dyk 2019', '5-0-0-0', false, false),

-- ============================ HORIZONTAL PUSH =============================
('bench-press','Développé Couché','Bench Press','Bench Press','horizontal_push','barbell','intermediate',
 array['chest','triceps'], array['shoulders'],
 array['strength','functional','fat_loss']::workout_goal[],
 'Coudes 45°, omoplates serrées, barre touche poitrine, pousse explosif.',
 'Elbows 45°, shoulder blades retracted, bar touches chest, explosive press.',
 'Ellebogen 45°, schouderbladen ingetrokken, stang raakt borst, explosieve druk.',
 'red',
 'Coudes à 90° = risque épaule à long terme. Garde-les à 45-60°.',
 'Elbows at 90° = long-term shoulder risk. Keep at 45-60°.',
 'Ellebogen op 90° = schouderprobleem op lange termijn. Houd op 45-60°.',
 'Green 2007', '2-1-1-0', false, true),

('dumbbell-press','Développé Haltères','Dumbbell Bench Press','Halter Bankdrukken','horizontal_push','dumbbell','beginner',
 array['chest','triceps'], array['shoulders','core'],
 array['strength','fat_loss','functional']::workout_goal[],
 'Haltères en pronation, coudes 45°, descends jusqu''au niveau poitrine, pousse.',
 'Pronated grip, elbows 45°, lower to chest level, press up.',
 'Pronated greep, ellebogen 45°, daal tot borsthoogte, druk omhoog.',
 'blue',
 'Amplitude 30% supérieure à la barre, mieux pour hypertrophie.',
 '30% greater range than barbell, better for hypertrophy.',
 '30% groter bereik dan halter, beter voor hypertrofie.',
 'Saeterbakken 2011', '2-1-1-0', false, false),

('push-up','Pompe','Push-Up','Push-Up','horizontal_push','bodyweight','beginner',
 array['chest','triceps'], array['shoulders','core'],
 array['fat_loss','functional','travel_home']::workout_goal[],
 'Mains largeur épaules, corps gainé en planche, descends poitrine au sol.',
 'Hands shoulder-width, body braced like a plank, chest to floor.',
 'Handen op schouderbreedte, lichaam als plank, borst naar vloer.',
 'blue', null, null, null, null, '2-1-1-0', false, false),

('decline-push-up','Pompe Pieds Surélevés','Decline Push-Up','Decline Push-Up','horizontal_push','bodyweight','intermediate',
 array['chest','shoulders'], array['triceps','core'],
 array['fat_loss','travel_home']::workout_goal[],
 'Pieds sur banc, mains au sol, descends poitrine, plus de stress haut pectoraux.',
 'Feet on bench, hands on floor, lower chest, more upper-pec stress.',
 'Voeten op bank, handen op vloer, daal borst, meer stress bovenste borst.',
 'blue', null, null, null, null, '2-1-1-0', false, false),

('dumbbell-fly','Écarté Haltères','Dumbbell Fly','Dumbbell Fly','horizontal_push','dumbbell','intermediate',
 array['chest'], array['shoulders'],
 array['strength']::workout_goal[],
 'Allongé, légère flexion coudes, ouvre en arc, étirement contrôlé.',
 'Lying down, slight elbow bend, open in arc, controlled stretch.',
 'Liggend, lichte ellebogenbocht, open in boog, gecontroleerde rek.',
 'red',
 'Coudes complètement tendus = blessure du long biceps assurée.',
 'Fully locked elbows = guaranteed long-head biceps injury.',
 'Volledig vergrendelde ellebogen = gegarandeerde lange biceps blessure.',
 null, '3-1-1-0', false, false),

-- ============================ VERTICAL PUSH ===============================
('overhead-press','Développé Militaire','Overhead Press','Schouderdrukken','vertical_push','barbell','intermediate',
 array['shoulders','triceps'], array['core','upper_back'],
 array['strength','functional']::workout_goal[],
 'Barre poitrine, gainage abdo + fessiers, pousse vertical, tête traverse à la fin.',
 'Bar at chest, brace abs + glutes, press vertically, head through at top.',
 'Stang op borst, span buik + bilspieren, verticaal duwen, hoofd door bovenaan.',
 'red',
 'Cambrer le bas du dos = douleurs lombaires garanties à long terme.',
 'Lower-back arch = guaranteed long-term lumbar pain.',
 'Onderrug doorbuigen = gegarandeerde lange-termijn lumbale pijn.',
 'McGill 2014', '2-1-1-0', false, false),

('push-press','Push Press','Push Press','Push Press','vertical_push','barbell','intermediate',
 array['shoulders','quadriceps'], array['triceps','core'],
 array['strength','functional','sport']::workout_goal[],
 'Léger dip jambes, transmet l''énergie via les bras, finis bras tendus.',
 'Slight leg dip, transmit energy via arms, finish arms locked.',
 'Lichte beendip, breng energie over via armen, eindig met gestrekte armen.',
 'violet',
 'Permet 20-30% de charge en plus que le strict press, idéal en CrossFit.',
 'Allows 20-30% more load than strict press, ideal for CrossFit.',
 'Geeft 20-30% meer belasting dan strict press, ideaal voor CrossFit.',
 null, '1-1-1-0', false, false),

('handstand-push-up','HSPU','Handstand Push-Up','Handstand Push-Up','vertical_push','bodyweight','advanced',
 array['shoulders','triceps'], array['core'],
 array['functional']::workout_goal[],
 'Contre mur, mains près du mur, descends tête, pousse explosif vers le haut.',
 'Against wall, hands close, lower head, explosive press up.',
 'Tegen muur, handen dichtbij, hoofd omlaag, explosieve druk omhoog.',
 'red',
 'Pas avant de tenir un handstand 30s libre, sinon risque cervical.',
 'Not before holding a free handstand 30s, otherwise cervical risk.',
 'Niet voor je een vrije handstand 30s vasthoudt, anders nekprobleem.',
 null, '2-1-1-0', false, false),

('dumbbell-shoulder-press','Développé Haltères','Dumbbell Shoulder Press','Halter Schouderdrukken','vertical_push','dumbbell','beginner',
 array['shoulders','triceps'], array['core'],
 array['strength','fat_loss','travel_home']::workout_goal[],
 'Haltères niveau oreilles, coudes légèrement en avant, pousse vertical.',
 'Dumbbells at ear level, elbows slightly forward, press vertically.',
 'Halters op oorhoogte, ellebogen iets vooruit, verticaal duwen.',
 'blue', null, null, null, null, '2-1-1-0', false, false),

-- ============================ HORIZONTAL PULL =============================
('barbell-row','Rowing Barre','Barbell Row','Barbell Row','horizontal_pull','barbell','intermediate',
 array['lats','upper_back'], array['biceps','erectors'],
 array['strength','functional']::workout_goal[],
 'Buste à 45°, dos neutre, tire barre vers nombril, contracte omoplates.',
 'Torso at 45°, neutral spine, pull bar to navel, squeeze shoulder blades.',
 'Romp 45°, rug neutraal, trek stang naar navel, knijp schouderbladen.',
 'red',
 'Dos arrondi = élévation pression discale 1.4x — risque hernie.',
 'Rounded back = 1.4x disc pressure — hernia risk.',
 'Afgeronde rug = 1,4x discusdruk — hernia risico.',
 'McGill 2014', '2-1-1-0', false, false),

('dumbbell-row','Rowing Haltère','Dumbbell Row','Dumbbell Row','horizontal_pull','dumbbell','beginner',
 array['lats','upper_back'], array['biceps','core'],
 array['strength','fat_loss','functional']::workout_goal[],
 'Genou + main sur banc, tire l''haltère vers la hanche, contrôle descente.',
 'Knee + hand on bench, pull dumbbell to hip, controlled descent.',
 'Knie + hand op bank, trek halter naar heup, gecontroleerde daling.',
 'blue', null, null, null, null, '2-1-1-0', true, false),

('inverted-row','Rowing Australien','Inverted Row','Australische Pull-Up','horizontal_pull','bodyweight','beginner',
 array['upper_back','lats'], array['biceps','core'],
 array['fat_loss','functional','travel_home']::workout_goal[],
 'Sous une barre fixe, corps gainé, tire poitrine vers la barre.',
 'Under a fixed bar, body braced, pull chest to bar.',
 'Onder een vaste stang, lichaam gespannen, trek borst naar stang.',
 'blue', null, null, null, null, '2-1-1-0', false, false),

('cable-row','Rowing Poulie','Cable Row','Kabel Roeien','horizontal_pull','cable','beginner',
 array['lats','upper_back'], array['biceps'],
 array['strength','fat_loss']::workout_goal[],
 'Assis, jambes légèrement fléchies, tire vers le nombril, contracte 1s.',
 'Seated, knees slightly bent, pull to navel, squeeze 1s.',
 'Zittend, knieën licht gebogen, trek naar navel, knijp 1s.',
 'blue', null, null, null, null, '2-1-1-0', false, false),

-- ============================ VERTICAL PULL ===============================
('pull-up','Traction Pronation','Pull-Up','Pull-Up','vertical_pull','bodyweight','intermediate',
 array['lats','upper_back'], array['biceps','core'],
 array['strength','functional']::workout_goal[],
 'Prise pronation largeur épaules, monte menton au-dessus barre, descente contrôlée.',
 'Pronated grip shoulder-width, chin above bar, controlled descent.',
 'Pronated greep schouderbreedte, kin boven stang, gecontroleerde daling.',
 'green',
 'Mouvement le plus efficace pour développer largeur du dos (EMG max).',
 'Most effective movement for back width development (max EMG).',
 'Meest effectieve oefening voor rugbreedte (max EMG).',
 'Youdas 2010', '2-1-1-0', false, false),

('chin-up','Traction Supination','Chin-Up','Chin-Up','vertical_pull','bodyweight','intermediate',
 array['biceps','lats'], array['upper_back','core'],
 array['strength','functional']::workout_goal[],
 'Prise supination, plus accessible que pronation, focus biceps + dos.',
 'Supinated grip, more accessible than pronated, biceps + back focus.',
 'Supinated greep, toegankelijker dan pronated, biceps + rug focus.',
 'blue', null, null, null, null, '2-1-1-0', false, false),

('lat-pulldown','Tirage Vertical','Lat Pulldown','Lat Pulldown','vertical_pull','cable','beginner',
 array['lats'], array['biceps','upper_back'],
 array['strength','fat_loss']::workout_goal[],
 'Tire la barre vers le haut de la poitrine, coudes vers les hanches.',
 'Pull bar to upper chest, elbows toward hips.',
 'Trek stang naar bovenste borst, ellebogen naar heupen.',
 'red',
 'Tirage derrière la nuque = risque épaule + cervicales.',
 'Behind-the-neck pulldown = shoulder + cervical risk.',
 'Achter-de-nek pulldown = schouder + cervicaal risico.',
 'Durall 2009', '2-1-1-0', false, false),

('muscle-up','Muscle-Up','Muscle-Up','Muscle-Up','gymnastics','bodyweight','advanced',
 array['lats','triceps','chest'], array['core','biceps'],
 array['functional']::workout_goal[],
 'Traction explosive + dip, transition rapide, kipping ou strict.',
 'Explosive pull + dip, fast transition, kipping or strict.',
 'Explosieve trek + dip, snelle overgang, kipping of strict.',
 'red',
 'Pré-requis : 10 tractions strictes + 10 dips strictes minimum.',
 'Prerequisite: 10 strict pull-ups + 10 strict dips minimum.',
 'Vereiste: 10 strikte pull-ups + 10 strikte dips minimum.',
 null, null, false, false),

('toes-to-bar','Pieds à la Barre','Toes to Bar','Tenen aan Stang','core','bodyweight','intermediate',
 array['core','lats'], array['hip_flexors'],
 array['functional']::workout_goal[],
 'Suspendu à barre, pieds touchent la barre, contrôle descente.',
 'Hanging from bar, feet touch bar, controlled descent.',
 'Hangend aan stang, voeten raken stang, gecontroleerde daling.',
 'violet',
 'Mouvement signature CrossFit Open, RX = 30 reps non-stop.',
 'CrossFit Open signature movement, RX = 30 unbroken reps.',
 'CrossFit Open kenmerkende beweging, RX = 30 reps non-stop.',
 null, null, false, false),

-- ================================ CARRY ===================================
('farmer-carry','Marche du Fermier','Farmer Carry','Farmer Carry','carry','dumbbell','beginner',
 array['core','traps','forearms'], array['glutes','quadriceps'],
 array['strength','functional','sport']::workout_goal[],
 'Lourd dans chaque main, marche droit, épaules en arrière, gainage maximal.',
 'Heavy in each hand, walk straight, shoulders back, maximal brace.',
 'Zwaar in elke hand, loop rechtdoor, schouders naar achter, maximale spanning.',
 'green',
 'Stimule plus de muscles posturaux que n''importe quel exercice isolé.',
 'Recruits more postural muscles than any isolated exercise.',
 'Activeert meer postuurspieren dan welke geïsoleerde oefening dan ook.',
 'McGill 2009', null, false, false),

('sandbag-carry','Marche Sandbag','Sandbag Carry','Sandbag Carry','carry','sandbag','intermediate',
 array['core','upper_back'], array['glutes','quadriceps'],
 array['functional','sport']::workout_goal[],
 'Sandbag sur épaule ou poitrine, marche stable, alterne épaules toutes les 25m.',
 'Sandbag on shoulder or chest, stable walk, alternate shoulders every 25m.',
 'Sandbag op schouder of borst, stabiel lopen, wissel schouders elke 25m.',
 'violet',
 'Station Hyrox 5 — exigence 2x20kg dames / 2x30kg hommes.',
 'Hyrox station 5 — 2x20kg women / 2x30kg men required.',
 'Hyrox station 5 — 2x20kg dames / 2x30kg heren vereist.',
 null, null, false, false),

('suitcase-carry','Marche Valise','Suitcase Carry','Koffer Carry','carry','dumbbell','beginner',
 array['core','obliques'], array['traps','forearms'],
 array['functional','sport']::workout_goal[],
 'Charge dans une seule main, anti-flexion latérale, épaules nivelées.',
 'Load in one hand only, anti-lateral-flexion, shoulders level.',
 'Belasting in één hand, anti-laterale flexie, schouders genivelleerd.',
 'green',
 'Prévention dos x2 vs farmer carry classique (Stuart McGill).',
 '2x more lower-back protective than standard farmer carry (Stuart McGill).',
 '2x meer rugbeschermend dan standaard farmer carry (Stuart McGill).',
 'McGill 2009', null, true, false),

-- ================================ CORE ====================================
('plank','Planche','Plank','Plank','core','bodyweight','beginner',
 array['core'], array['shoulders','glutes'],
 array['fat_loss','functional','travel_home','mobility']::workout_goal[],
 'Avant-bras au sol, corps droit comme une planche, gaine fessiers + abdo.',
 'Forearms on floor, body straight as a plank, brace glutes + abs.',
 'Onderarmen op vloer, lichaam recht als plank, span bilspieren + buik.',
 'blue',
 'Tenir 60s c''est l''objectif fonctionnel, au-delà = perte de spécificité.',
 'Holding 60s is the functional goal, beyond = loss of specificity.',
 'Vasthouden 60s is functioneel doel, daarboven = verlies van specificiteit.',
 'McGill 2010', null, false, false),

('side-plank','Planche Latérale','Side Plank','Zijplank','core','bodyweight','beginner',
 array['obliques','core'], array['shoulders','glutes'],
 array['fat_loss','sport','mobility']::workout_goal[],
 'Sur un avant-bras, corps droit, hanches hautes, alterne 30-45s par côté.',
 'On one forearm, body straight, hips high, alternate 30-45s per side.',
 'Op één onderarm, lichaam recht, heupen hoog, wissel 30-45s per kant.',
 'green',
 'Test McGill — équilibre droit/gauche prédit douleurs lombaires.',
 'McGill test — left/right balance predicts low-back pain.',
 'McGill test — links/rechts balans voorspelt lage-rugpijn.',
 'McGill 2002', null, true, false),

('hollow-body-hold','Hollow Body','Hollow Body','Hollow Body','core','bodyweight','intermediate',
 array['core'], array['hip_flexors'],
 array['functional']::workout_goal[],
 'Allongé, lombaires collées au sol, jambes et bras tendus, position banane inversée.',
 'Lying down, lumbar pressed to floor, legs and arms straight, reverse banana position.',
 'Liggend, onderrug op vloer, benen en armen gestrekt, omgekeerde bananenpositie.',
 'green',
 'Position de référence en gymnastique — base de tous les skills barres.',
 'Reference position in gymnastics — base for all bar skills.',
 'Referentiehouding in turnen — basis voor alle stang skills.',
 null, null, false, false),

('hanging-leg-raise','Lever de Jambes Suspendu','Hanging Leg Raise','Hanging Leg Raise','core','bodyweight','intermediate',
 array['core'], array['hip_flexors','lats'],
 array['fat_loss','functional']::workout_goal[],
 'Suspendu, monte les jambes tendues à l''horizontale, contrôle descente.',
 'Hanging, raise straight legs to horizontal, controlled descent.',
 'Hangend, breng gestrekte benen horizontaal, gecontroleerde daling.',
 'blue', null, null, null, null, '2-0-1-0', false, false),

('dead-bug','Dead Bug','Dead Bug','Dead Bug','core','bodyweight','beginner',
 array['core'], array['hip_flexors'],
 array['mobility','sport','travel_home']::workout_goal[],
 'Allongé, lombaires collées, alterne bras-jambe opposés, contrôle parfait.',
 'Lying down, lumbar grounded, alternate opposite arm-leg, perfect control.',
 'Liggend, onderrug aangedrukt, wissel tegenovergestelde arm-been, perfecte controle.',
 'green',
 'Anti-extension lombaire — prévention #1 selon Stuart McGill.',
 'Lumbar anti-extension — McGill''s #1 prevention exercise.',
 'Lumbale anti-extensie — McGill''s #1 preventieve oefening.',
 'McGill 2002', '3-1-3-0', true, false),

('pallof-press','Pallof Press','Pallof Press','Pallof Press','core','cable','beginner',
 array['core','obliques'], array['shoulders'],
 array['sport','functional','mobility']::workout_goal[],
 'Câble latéral, pousse bras devant, résiste à la rotation du tronc.',
 'Cable lateral, press arms forward, resist trunk rotation.',
 'Kabel zijdelings, druk armen vooruit, weersta romp rotatie.',
 'green',
 'Anti-rotation — base de la stabilité du tronc en sport.',
 'Anti-rotation — foundation of trunk stability in sport.',
 'Anti-rotatie — basis van rompstabiliteit in sport.',
 'Boyle 2010', null, true, false),

('copenhagen-adduction','Copenhagen','Copenhagen Adduction','Copenhagen Adduction','core','bodyweight','intermediate',
 array['adductors','core'], array['glutes'],
 array['sport','functional']::workout_goal[],
 'Sur le côté, jambe haute sur banc, pousse jambe basse vers le haut.',
 'Side-lying, top leg on bench, drive bottom leg up.',
 'Zijligging, bovenste been op bank, duw onderste been omhoog.',
 'green',
 'Réduit blessures adducteurs de 41% chez footballeurs.',
 'Reduces adductor injuries by 41% in footballers.',
 'Vermindert adductorblessures met 41% bij voetballers.',
 'Harøy 2019', '3-0-3-0', true, false),

-- ============================== OLYMPIC ===================================
('clean','Épaulé','Clean','Clean','olympic','barbell','advanced',
 array['glutes','quadriceps','traps'], array['core','shoulders'],
 array['strength','functional','sport']::workout_goal[],
 '1er tirage lent jusqu''aux genoux, 2e tirage explosif, bascule + réception au rack.',
 '1st pull slow to knees, 2nd pull explosive, swing under + rack catch.',
 '1e trek langzaam tot knieën, 2e trek explosief, omdraaien + vangen op rack.',
 'red',
 'Apprendre la technique avant la charge — 80% des blessures = mauvaise technique.',
 'Learn technique before load — 80% of injuries = poor technique.',
 'Leer techniek voor belasting — 80% van blessures = slechte techniek.',
 'Hadi 2018', null, false, false),

('snatch','Arraché','Snatch','Snatch','olympic','barbell','advanced',
 array['glutes','quadriceps','shoulders'], array['core','traps'],
 array['strength','functional','sport']::workout_goal[],
 'Prise large, 1 mouvement complet sol→bras tendus au-dessus, réception en squat.',
 'Wide grip, 1 complete movement floor→arms locked overhead, squat catch.',
 'Brede greep, 1 volledige beweging vloer→armen gestrekt boven hoofd, squat vangst.',
 'red',
 'Mouvement le plus technique de l''haltérophilie — coach obligatoire.',
 'Most technical movement in weightlifting — coach mandatory.',
 'Meest technische beweging in gewichtheffen — coach verplicht.',
 null, null, false, false),

('jerk','Jeté','Jerk','Jerk','olympic','barbell','advanced',
 array['shoulders','triceps','quadriceps'], array['core'],
 array['strength','functional','sport']::workout_goal[],
 'Depuis rack, dip + drive vertical, split ou push, réception bras tendus.',
 'From rack, dip + vertical drive, split or push, lock arms overhead.',
 'Vanaf rack, dip + verticale drive, split of push, vergrendel armen boven.',
 'blue',
 'Permet 30% de charge en plus que push press grâce au dip + split.',
 'Allows 30% more load than push press via dip + split.',
 'Geeft 30% meer belasting dan push press via dip + split.',
 null, null, false, true),

('power-clean','Épaulé Debout','Power Clean','Power Clean','olympic','barbell','intermediate',
 array['glutes','quadriceps','traps'], array['core'],
 array['strength','functional','sport']::workout_goal[],
 'Épaulé sans descente en squat profond — réception parallèle.',
 'Clean without deep squat catch — parallel catch.',
 'Clean zonder diepe squat-vangst — parallelle vangst.',
 'violet',
 'Référence puissance — utilisé par 90% des prép physiques NFL/NBA.',
 'Power benchmark — used by 90% of NFL/NBA S&C coaches.',
 'Krachtreferentie — gebruikt door 90% van NFL/NBA S&C coaches.',
 null, null, false, false),

-- ============================== JUMP / PLYO ===============================
('box-jump','Box Jump','Box Jump','Box Jump','jump','box','intermediate',
 array['quadriceps','glutes','calves'], array['core'],
 array['fat_loss','sport','functional']::workout_goal[],
 'Charge sur boîte, balance bras, atterris souple en demi-squat, descends en marchant.',
 'Charge to box, swing arms, soft landing in half-squat, step down.',
 'Spring naar box, zwaai armen, zachte landing in halfsquat, stap af.',
 'red',
 'Sauter en bas = micro-traumatismes répétés — descends toujours en marchant.',
 'Jumping down = repetitive micro-trauma — always step down.',
 'Naar beneden springen = herhaalde micro-trauma — altijd aflopen.',
 null, null, false, false),

('depth-jump','Depth Jump','Depth Jump','Depth Jump','jump','box','advanced',
 array['quadriceps','glutes','calves'], array['core'],
 array['sport']::workout_goal[],
 'Descends de la boîte, dès contact saute max haut, contact sol < 0.2s.',
 'Step off box, on contact jump max high, ground contact < 0.2s.',
 'Stap van box, bij contact spring maximaal hoog, grondcontact < 0,2s.',
 'green',
 'Méthode Verkhoshansky — augmente vitesse explosive de 8-12%.',
 'Verkhoshansky method — increases explosive speed by 8-12%.',
 'Verkhoshansky methode — verhoogt explosieve snelheid met 8-12%.',
 'Verkhoshansky 1969', null, false, false),

('broad-jump','Saut en Longueur','Broad Jump','Verspringen','jump','bodyweight','beginner',
 array['quadriceps','glutes'], array['calves','core'],
 array['sport','functional']::workout_goal[],
 'Pieds parallèles, balance bras, saute le plus loin, atterris stable.',
 'Feet parallel, swing arms, jump as far as possible, stable landing.',
 'Voeten parallel, zwaai armen, spring zo ver mogelijk, stabiele landing.',
 'blue',
 'Test puissance — norme pro foot 240cm hommes / 200cm dames.',
 'Power test — pro football norm 240cm men / 200cm women.',
 'Krachttest — pro voetbal norm 240cm heren / 200cm dames.',
 'NFL Combine', null, false, false),

-- =========================== GAIT (run/sprint/sled) =======================
('sprint-30m','Sprint 30m','30m Sprint','30m Sprint','gait','run','intermediate',
 array['glutes','hamstrings','calves'], array['core'],
 array['sport','fat_loss']::workout_goal[],
 'Position 3-points, accélération progressive, posture penchée 5-10m.',
 '3-point start, progressive acceleration, forward lean 5-10m.',
 '3-puntsstart, progressieve acceleratie, voorovergebogen 5-10m.',
 'green',
 'Test référence : <4.0s (foot pro), 4.0-4.4s (semi-pro), >4.4s (amateur).',
 'Reference test: <4.0s (pro footballer), 4.0-4.4s (semi-pro), >4.4s (amateur).',
 'Referentietest: <4.0s (profvoetballer), 4.0-4.4s (semi-pro), >4.4s (amateur).',
 'Wisløff 2004', null, false, false),

('shuttle-run','Shuttle Run','Shuttle Run','Shuttle Run','gait','run','intermediate',
 array['quadriceps','glutes'], array['core'],
 array['sport','fat_loss','functional']::workout_goal[],
 '5m-10m-5m avec changements de direction, touche au sol à chaque cône.',
 '5m-10m-5m with changes of direction, ground touch each cone.',
 '5m-10m-5m met richtingsveranderingen, grondaanraking bij elke kegel.',
 'violet',
 'Capacité COD — corrélée à la performance match en foot/hockey.',
 'COD capacity — correlated to match performance in football/hockey.',
 'COD-capaciteit — gecorreleerd aan wedstrijdprestatie in voetbal/hockey.',
 'Sheppard 2006', null, false, false),

('sled-push','Poussée Traîneau','Sled Push','Sled Push','gait','sled','intermediate',
 array['quadriceps','glutes','calves'], array['core'],
 array['fat_loss','functional','sport']::workout_goal[],
 'Mains hautes ou basses, corps incliné 45°, pousse contrôlé, foulées rapides.',
 'Hands high or low, body angled 45°, controlled push, quick steps.',
 'Handen hoog of laag, lichaam onder 45°, gecontroleerde duw, snelle stappen.',
 'violet',
 'Station Hyrox 1 — 50m avec 152kg hommes / 102kg dames.',
 'Hyrox station 1 — 50m with 152kg men / 102kg women.',
 'Hyrox station 1 — 50m met 152kg heren / 102kg dames.',
 null, null, false, false),

('sled-pull','Tirage Traîneau','Sled Pull','Sled Pull','gait','sled','intermediate',
 array['lats','hamstrings'], array['core','biceps'],
 array['functional','sport']::workout_goal[],
 'Corde ou sangle, recule en tirant, jambes fléchies, dos neutre.',
 'Rope or strap, walk backward pulling, knees bent, neutral spine.',
 'Touw of riem, achterwaarts lopen trekkend, knieën gebogen, rug neutraal.',
 'violet',
 'Station Hyrox 2 — 50m avec 103kg hommes / 78kg dames.',
 'Hyrox station 2 — 50m with 103kg men / 78kg women.',
 'Hyrox station 2 — 50m met 103kg heren / 78kg dames.',
 null, null, false, false),

('run-easy','Course Facile','Easy Run','Easy Run','gait','run','beginner',
 array['glutes','hamstrings','calves'], array['core'],
 array['fat_loss','sport','mobility']::workout_goal[],
 'Allure conversationnelle, FC 60-70% max, posture droite, foulée naturelle.',
 'Conversational pace, HR 60-70% max, upright posture, natural stride.',
 'Conversatietempo, HR 60-70% max, rechte houding, natuurlijke pas.',
 'green',
 'Zone 2 — base aérobie, 80% du volume des coureurs élite.',
 'Zone 2 — aerobic base, 80% of elite runners'' volume.',
 'Zone 2 — aerobe basis, 80% van het volume van topatleten.',
 'Seiler 2010', null, false, false),

('run-tempo','Tempo','Tempo Run','Tempo Run','gait','run','intermediate',
 array['glutes','hamstrings','calves'], array['core'],
 array['sport','fat_loss']::workout_goal[],
 'Allure seuil, FC 85-90% max, soutenable 20-40min.',
 'Threshold pace, HR 85-90% max, sustainable 20-40min.',
 'Drempeltempo, HR 85-90% max, vol te houden 20-40min.',
 'blue',
 'Améliore le seuil lactique de 5-8% en 6 semaines.',
 'Improves lactate threshold by 5-8% in 6 weeks.',
 'Verbetert lactaatdrempel met 5-8% in 6 weken.',
 'Helgerud 2007', null, false, false),

('run-vo2max','4x4 VO2max','4x4 VO2max','4x4 VO2max','gait','run','advanced',
 array['glutes','hamstrings','calves'], array['core'],
 array['sport']::workout_goal[],
 '4 min à 90-95% FCmax, 3 min récup actif, 4 répétitions.',
 '4 min at 90-95% HRmax, 3 min active recovery, 4 reps.',
 '4 min op 90-95% HRmax, 3 min actief herstel, 4 herhalingen.',
 'green',
 'Méthode Helgerud — augmente VO2max de 0.5 ml/kg/min par semaine.',
 'Helgerud method — increases VO2max by 0.5 ml/kg/min per week.',
 'Helgerud methode — verhoogt VO2max met 0,5 ml/kg/min per week.',
 'Helgerud 2007', null, false, false),

('30-15-ift','30-15 IFT','30-15 IFT','30-15 IFT','gait','run','advanced',
 array['glutes','hamstrings','calves'], array['core'],
 array['sport']::workout_goal[],
 '30s course intermittente avec changements de direction, 15s récup, x atteint épuisement.',
 '30s intermittent run with COD, 15s recovery, until exhaustion.',
 '30s intermitterend lopen met COD, 15s herstel, tot uitputting.',
 'green',
 'Test Buchheit — référence individuelle d''intensité pour foot/rugby/hockey.',
 'Buchheit test — individual intensity reference for football/rugby/hockey.',
 'Buchheit test — individuele intensiteitsreferentie voor voetbal/rugby/hockey.',
 'Buchheit 2010', null, false, false),

-- =========================== ROW / SKI / BIKE =============================
('rowing-erg','Aviron','Rowing Erg','Rowing Erg','gait','rower','beginner',
 array['lats','glutes','hamstrings'], array['core','biceps','quadriceps'],
 array['fat_loss','functional','sport']::workout_goal[],
 'Catch jambes pliées, drive jambes→hanches→bras, finish bras au sternum.',
 'Catch knees bent, drive legs→hips→arms, finish arms to sternum.',
 'Catch knieën gebogen, drive benen→heupen→armen, finish armen naar borstbeen.',
 'blue',
 'Station Hyrox 4 — 1km en 3''30-4''30 selon niveau.',
 'Hyrox station 4 — 1km in 3''30-4''30 by level.',
 'Hyrox station 4 — 1km in 3''30-4''30 afhankelijk van niveau.',
 null, null, false, false),

('ski-erg','Ski Erg','Ski Erg','Ski Erg','gait','ski_erg','beginner',
 array['lats','core','triceps'], array['glutes','hamstrings'],
 array['fat_loss','functional','sport']::workout_goal[],
 'Tire bras vers les hanches, fléchis hanches, garde les bras tendus en début.',
 'Pull arms to hips, hinge hips, keep arms extended at start.',
 'Trek armen naar heupen, knik heupen, houd armen gestrekt bij start.',
 'violet',
 'Station Hyrox 3 — 1km de ski-erg, ne pas démarrer trop fort.',
 'Hyrox station 3 — 1km of ski-erg, don''t start too hard.',
 'Hyrox station 3 — 1km ski-erg, niet te hard beginnen.',
 null, null, false, false),

('assault-bike','Vélo Air','Assault Bike','Assault Bike','gait','bike','beginner',
 array['quadriceps','glutes'], array['core','shoulders'],
 array['fat_loss','functional','sport']::workout_goal[],
 'Bras et jambes synchronisés, pousse + tire, intensité brutale possible.',
 'Arms and legs synchronized, push + pull, brutal intensity possible.',
 'Armen en benen gesynchroniseerd, duwen + trekken, brute intensiteit mogelijk.',
 'blue', null, null, null, null, null, false, false),

-- =========================== METCON / FUNCTIONAL ==========================
('thruster','Thruster','Thruster','Thruster','squat','barbell','intermediate',
 array['quadriceps','shoulders','glutes'], array['core','triceps'],
 array['fat_loss','functional','sport']::workout_goal[],
 'Front squat + push press, mouvement continu, transmission par les jambes.',
 'Front squat + push press, continuous movement, leg transmission.',
 'Front squat + push press, continue beweging, beentransmissie.',
 'red',
 'Mouvement signature CrossFit — un des plus exigeants cardio + force.',
 'CrossFit signature — one of the most demanding cardio + strength.',
 'CrossFit kenmerk — een van de meest veeleisende cardio + kracht.',
 null, '1-1-1-0', false, false),

('wall-ball','Wall Ball','Wall Ball','Wall Ball','squat','wall_ball','beginner',
 array['quadriceps','shoulders','glutes'], array['core'],
 array['fat_loss','functional','sport']::workout_goal[],
 'Squat profond, projette ballon vers cible (3m hommes / 2.7m dames), réceptionne, enchaîne.',
 'Deep squat, throw ball to target (3m men / 2.7m women), catch, repeat.',
 'Diepe squat, gooi bal naar doel (3m heren / 2,7m dames), vang, herhaal.',
 'violet',
 'Station Hyrox 8 (finale) — 100 reps, RX = 9kg hommes / 6kg dames.',
 'Hyrox station 8 (finale) — 100 reps, RX = 9kg men / 6kg women.',
 'Hyrox station 8 (finale) — 100 reps, RX = 9kg heren / 6kg dames.',
 null, null, false, false),

('burpee','Burpee','Burpee','Burpee','functional'::movement_pattern, 'bodyweight','beginner',
 array['core','chest'], array['quadriceps','shoulders'],
 array['fat_loss','functional','travel_home']::workout_goal[],
 'Squat → planche → pompe (option) → squat → saut + claquement mains.',
 'Squat → plank → push-up (option) → squat → jump + clap.',
 'Squat → plank → push-up (optie) → squat → spring + klap.',
 'blue',
 '20 burpees consécutifs élèvent FC à 90% max chez sujet entraîné.',
 '20 consecutive burpees raise HR to 90% max in trained subject.',
 '20 opeenvolgende burpees verhogen HR naar 90% max bij getrainde proefpersoon.',
 null, null, false, false),

('burpee-broad-jump','Burpee + Saut','Burpee Broad Jump','Burpee Broad Jump','functional'::movement_pattern, 'bodyweight','intermediate',
 array['core','quadriceps','glutes'], array['chest','shoulders'],
 array['fat_loss','functional','sport']::workout_goal[],
 'Burpee + saut en longueur après, progression métrée.',
 'Burpee + broad jump after, measured progression.',
 'Burpee + verspringen achteraf, gemeten progressie.',
 'violet',
 'Station Hyrox 6 — 80m de burpee broad jumps non-stop.',
 'Hyrox station 6 — 80m of burpee broad jumps unbroken.',
 'Hyrox station 6 — 80m burpee broad jumps non-stop.',
 null, null, false, false),

('mountain-climber','Mountain Climber','Mountain Climber','Mountain Climber','core','bodyweight','beginner',
 array['core'], array['shoulders','hip_flexors'],
 array['fat_loss','travel_home']::workout_goal[],
 'Position planche, alterne genoux vers la poitrine rapidement.',
 'Plank position, alternate knees to chest rapidly.',
 'Plankpositie, wissel knieën snel naar borst.',
 'blue', null, null, null, null, null, false, false),

('devil-press','Devil Press','Devil Press','Devil Press','functional'::movement_pattern, 'dumbbell','intermediate',
 array['shoulders','chest','glutes'], array['core'],
 array['fat_loss','functional']::workout_goal[],
 'Burpee avec haltères + arraché final au-dessus, mouvement continu.',
 'Burpee with dumbbells + final overhead snatch, continuous.',
 'Burpee met halters + finale overhead snatch, continu.',
 'red',
 'Très technique — apprends d''abord le burpee et l''arraché DB séparément.',
 'Highly technical — learn burpee and DB snatch separately first.',
 'Erg technisch — leer burpee en DB snatch eerst apart.',
 null, null, false, false),

('man-maker','Man Maker','Man Maker','Man Maker','functional'::movement_pattern, 'dumbbell','intermediate',
 array['shoulders','chest','glutes'], array['core','lats'],
 array['fat_loss','functional']::workout_goal[],
 'Burpee + 2 rowings + clean + thruster — un des plus complets.',
 'Burpee + 2 rows + clean + thruster — one of the most complete.',
 'Burpee + 2 rows + clean + thruster — een van de meest complete.',
 'blue', null, null, null, null, null, false, false),

-- ============================ MOBILITY / WARMUP ============================
('world-greatest-stretch','World''s Greatest Stretch','World''s Greatest Stretch','World''s Greatest Stretch','mobility','bodyweight','beginner',
 array['hips','thoracic'], array['hamstrings','adductors'],
 array['mobility','sport','travel_home']::workout_goal[],
 'Fente avant + rotation thoracique, alterne 30s par côté.',
 'Forward lunge + thoracic rotation, alternate 30s per side.',
 'Voorwaartse lunge + thoracale rotatie, wissel 30s per kant.',
 'green',
 'Mobilité globale en 1 mouvement — recommandé en échauffement avant chaque séance.',
 'Global mobility in 1 movement — recommended warm-up before any session.',
 'Globale mobiliteit in 1 beweging — aanbevolen opwarming voor elke sessie.',
 null, null, true, false),

('hip-90-90','Hip 90/90','Hip 90/90','Hip 90/90','mobility','bodyweight','beginner',
 array['hips'], null,
 array['mobility']::workout_goal[],
 'Assis jambe avant 90°, jambe arrière 90°, alterne rotation.',
 'Seated front leg 90°, back leg 90°, alternate rotation.',
 'Zittend voorste been 90°, achterste been 90°, wissel rotatie.',
 'blue', null, null, null, null, null, true, false),

('cat-cow','Chat-Vache','Cat-Cow','Cat-Cow','mobility','bodyweight','beginner',
 array['spine'], null,
 array['mobility','travel_home']::workout_goal[],
 'À 4 pattes, alterne arrondir et creuser le dos, respiration lente.',
 'On all fours, alternate rounding and arching back, slow breathing.',
 'Op handen en knieën, wissel rug afronden en doorbuigen, langzame ademhaling.',
 'blue', null, null, null, null, null, false, false),

('pigeon-pose','Pigeon','Pigeon Pose','Duif Houding','mobility','bodyweight','beginner',
 array['hips','glutes'], null,
 array['mobility','sport']::workout_goal[],
 'Genou avant 90° au sol, jambe arrière tendue, descends torse, 60s par côté.',
 'Front knee 90° on floor, back leg straight, lower torso, 60s per side.',
 'Voorste knie 90° op vloer, achterste been gestrekt, breng romp omlaag, 60s per kant.',
 'blue', null, null, null, null, null, true, false),

('thread-the-needle','Thread the Needle','Thread the Needle','Thread the Needle','mobility','bodyweight','beginner',
 array['thoracic','shoulders'], null,
 array['mobility','travel_home']::workout_goal[],
 'À 4 pattes, glisse un bras sous l''autre, rotation thoracique.',
 'On all fours, slide one arm under the other, thoracic rotation.',
 'Op handen en knieën, schuif arm onder de andere, thoracale rotatie.',
 'blue', null, null, null, null, null, true, false),

('foam-roll-quads','Auto-Massage Quads','Foam Roll Quads','Foam Roll Quads','mobility','bodyweight','beginner',
 array['quadriceps'], null,
 array['mobility','travel_home']::workout_goal[],
 'Sur le rouleau, déroule lentement haut→bas, 60-90s par jambe.',
 'On the foam roller, slowly roll up→down, 60-90s per leg.',
 'Op de foam roller, rol langzaam op→neer, 60-90s per been.',
 'green',
 'Améliore la mobilité de 10° en 60s sans diminuer la performance.',
 'Improves mobility by 10° in 60s without performance loss.',
 'Verbetert mobiliteit met 10° in 60s zonder prestatieverlies.',
 'MacDonald 2013', null, true, false),

('fifa-11','FIFA 11+','FIFA 11+','FIFA 11+','mobility','bodyweight','beginner',
 array['core','glutes','hamstrings'], array['adductors'],
 array['sport','mobility']::workout_goal[],
 'Protocole 15 min — course technique + force + équilibre + plyo + cool-down.',
 '15 min protocol — technical run + strength + balance + plyo + cool-down.',
 '15 min protocol — technische loop + kracht + evenwicht + plyo + cool-down.',
 'green',
 'Réduit blessures footballeurs de 30-50% — protocole UEFA officiel.',
 'Reduces footballer injuries by 30-50% — official UEFA protocol.',
 'Vermindert voetbalblessures met 30-50% — officieel UEFA protocol.',
 'Soligard 2008', null, false, false),

-- =========================== ARM ACCESSORIES ==============================
('biceps-curl','Curl Biceps','Biceps Curl','Biceps Curl','horizontal_pull','dumbbell','beginner',
 array['biceps'], array['forearms'],
 array['strength','fat_loss']::workout_goal[],
 'Coudes fixes contre le corps, supination en montée, contrôle descente.',
 'Elbows fixed against body, supinate on the way up, control descent.',
 'Ellebogen vast tegen lichaam, supineren op de weg omhoog, controleer daling.',
 'blue', null, null, null, null, '2-1-1-0', false, false),

('hammer-curl','Curl Marteau','Hammer Curl','Hamer Curl','horizontal_pull','dumbbell','beginner',
 array['biceps','brachialis'], array['forearms'],
 array['strength']::workout_goal[],
 'Prise neutre, monte sans rotation, focus brachial + brachioradial.',
 'Neutral grip, raise without rotation, focus on brachialis + brachioradialis.',
 'Neutrale greep, hef zonder rotatie, focus op brachialis + brachioradialis.',
 'green',
 'Cible le brachial — muscle clé pour la circonférence du bras.',
 'Targets the brachialis — key muscle for arm circumference.',
 'Richt op brachialis — sleutelspier voor armomtrek.',
 null, '2-1-1-0', false, false),

('triceps-pushdown','Extension Triceps','Triceps Pushdown','Triceps Pushdown','vertical_push','cable','beginner',
 array['triceps'], null,
 array['strength']::workout_goal[],
 'Coudes fixes, extension complète, contrôle remontée.',
 'Elbows fixed, full extension, controlled return.',
 'Ellebogen vast, volledige extensie, gecontroleerde terugkeer.',
 'blue', null, null, null, null, '2-1-1-0', false, false),

('dips','Dips','Dips','Dips','vertical_push','bodyweight','intermediate',
 array['triceps','chest'], array['shoulders'],
 array['strength','functional']::workout_goal[],
 'Barres parallèles, descends jusqu''à coudes 90°, pousse vertical.',
 'Parallel bars, descend until elbows 90°, vertical press.',
 'Parallelle stangen, daal tot ellebogen 90°, verticaal duwen.',
 'red',
 'Descente trop basse = stress acromio-claviculaire — stop à 90°.',
 'Too deep = AC joint stress — stop at 90°.',
 'Te diep = AC-gewricht stress — stop op 90°.',
 'Bayraktar 2017', '2-1-1-0', false, false),

-- ============================== CALVES ====================================
('standing-calf-raise','Mollet Debout','Standing Calf Raise','Standing Calf Raise','vertical_push','machine','beginner',
 array['calves'], null,
 array['strength','sport']::workout_goal[],
 'Étirement complet en bas, contraction max en haut, 1s pause.',
 'Full stretch at bottom, max contraction at top, 1s pause.',
 'Volledige strek onderaan, max contractie bovenaan, 1s pauze.',
 'blue', null, null, null, null, '2-1-2-0', false, false),

('jump-rope','Corde à Sauter','Jump Rope','Springtouw','jump','bodyweight','beginner',
 array['calves'], array['core','shoulders'],
 array['fat_loss','sport','travel_home']::workout_goal[],
 'Petits sauts sur la pointe des pieds, poignets dirigent, regard avant.',
 'Small jumps on toes, wrists drive rope, eyes forward.',
 'Kleine sprongen op tenen, polsen sturen touw, blik vooruit.',
 'green',
 '10 min de corde = 30 min de course en dépense calorique.',
 '10 min jump rope = 30 min running in caloric expenditure.',
 '10 min springtouw = 30 min hardlopen in calorisch verbruik.',
 'Baker 1968', null, false, false),

-- ============================== POSTERIOR =================================
('face-pull','Face Pull','Face Pull','Face Pull','horizontal_pull','cable','beginner',
 array['rear_delts','upper_back'], array['rotator_cuff'],
 array['strength','mobility','sport']::workout_goal[],
 'Câble haut, tire vers le visage, coudes hauts, contracte omoplates.',
 'High cable, pull to face, elbows high, squeeze shoulder blades.',
 'Hoge kabel, trek naar gezicht, ellebogen hoog, knijp schouderbladen.',
 'green',
 'Prévention #1 des blessures épaule chez bench presser réguliers.',
 '#1 shoulder injury prevention for regular bench pressers.',
 '#1 schouder blessurepreventie voor regelmatige bench pressers.',
 'Cools 2014', '2-1-2-0', false, false),

('reverse-fly','Oiseau','Reverse Fly','Reverse Fly','horizontal_pull','dumbbell','beginner',
 array['rear_delts','upper_back'], null,
 array['strength','mobility']::workout_goal[],
 'Buste à 45°, ouvre les bras, contracte omoplates, descente contrôlée.',
 'Torso at 45°, open arms, squeeze blades, controlled descent.',
 'Romp 45°, open armen, knijp schouderbladen, gecontroleerde daling.',
 'blue', null, null, null, null, '2-1-1-0', false, false),

-- ============================ HYROX-SPECIFIC ==============================
('lunge-walking-loaded','Fente Marchée Chargée','Loaded Walking Lunge','Belaste Wandelende Lunge','lunge','sandbag','intermediate',
 array['quadriceps','glutes'], array['core'],
 array['functional','sport']::workout_goal[],
 'Sandbag sur épaules, fentes marchées 100m, alternance des jambes.',
 'Sandbag on shoulders, 100m walking lunges, alternating legs.',
 'Sandbag op schouders, 100m wandelende lunges, afwisselend benen.',
 'violet',
 'Station Hyrox 7 — 100m de fentes lestées 20kg dames / 30kg hommes.',
 'Hyrox station 7 — 100m loaded lunges 20kg women / 30kg men.',
 'Hyrox station 7 — 100m belaste lunges 20kg dames / 30kg heren.',
 null, '2-0-1-0', true, false);

-- ============================================================================
-- Sanity check
-- ============================================================================
do $$
declare v_count int;
begin
  select count(*) into v_count from public.exercises;
  raise notice 'Exercises seeded: %', v_count;
  if v_count < 80 then
    raise exception 'Expected at least 80 exercises, got %', v_count;
  end if;
end $$;
